# Generated by Django 5.2.6 on 2025-09-15 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swiftcarapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pName', models.CharField(blank=True, max_length=20, null=True)),
                ('pPrice', models.IntegerField(blank=True, max_length=6, null=True)),
                ('pDescription', models.CharField(blank=True, max_length=100, null=True)),
                ('pCategory', models.CharField(choices=[('apparel', 'Apparel'), ('accesories', 'Accessories'), ('shoes', 'Shoes'), ('suits', 'Suites'), ('gaming&spots', 'Gaming&sports')], default='apparel', max_length=20)),
                ('pGender', models.CharField(choices=[('ladies', 'Ladies'), ('gents', 'Gents'), ('unisex', 'Unisex'), ('kids', 'Kids')], default='unisex', max_length=20)),
                ('pImage', models.ImageField(blank=True, upload_to='pimages/')),
                ('pPostdate', models.DateField(auto_now=True)),
            ],
        ),
    ]
