# Generated by Django 5.2.6 on 2025-09-15 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swiftcarapp', '0002_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pPrice',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
